/**
 * HandLogStream Tests
 */

import { event_timeline } from '../app.test'
import type { HandLogEvent } from '../types/hand-log'
import { ApiType } from '../types/api'
import { BattleType } from '../types/game'
import PokerChaseService, { PokerChaseDB } from '../app'
import { IDBKeyRange, indexedDB } from 'fake-indexeddb'
import { Readable } from 'stream'

const expected: string = [
  // hand 1
  "Poker Game #384370064: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level II (100/200) - 2025-07-13 17:21:53",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #4 is the button",
  "Seat 1: 美遊 (6000 in chips)",
  "Seat 2: 凛 (6000 in chips)",
  "Seat 3: クロエ (6000 in chips)",
  "Seat 4: イリヤスフィール (6000 in chips)",
  "美遊: posts the ante 50",
  "凛: posts the ante 50",
  "クロエ: posts the ante 50",
  "イリヤスフィール: posts the ante 50",
  "美遊: posts small blind 100",
  "凛: posts big blind 200",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [3h 7h]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "クロエ: folds",
  "イリヤスフィール: folds",
  "美遊: folds",
  "Uncalled bet (100) returned to 凛",
  "凛 collected 400 from pot",
  "凛: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 400",
  "Seat 1: 美遊 (small blind) folded before Flop",
  "Seat 2: 凛 (big blind) collected (400)",
  "Seat 3: クロエ folded before Flop (didn't bet)",
  "Seat 4: イリヤスフィール (button) folded before Flop (didn't bet)",
  // hand 2
  "Poker Game #384370118: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level II (100/200) - 2025-07-13 17:22:02",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (5850 in chips)",
  "Seat 2: 凛 (6250 in chips)",
  "Seat 3: クロエ (5950 in chips)",
  "Seat 4: イリヤスフィール (5950 in chips)",
  "美遊: posts the ante 50",
  "凛: posts the ante 50",
  "クロエ: posts the ante 50",
  "イリヤスフィール: posts the ante 50",
  "凛: posts small blind 100",
  "クロエ: posts big blind 200",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [Qh 7c]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "イリヤスフィール: raises 400 to 600",
  "美遊: calls 600",
  "凛: folds",
  "クロエ: folds",
  "*** FLOP *** [Kc 2s Js]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** TURN *** [Kc 2s Js] [2c]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** RIVER *** [Kc 2s Js 2c] [2h]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** SHOW DOWN ***",
  "イリヤスフィール: shows [As 5h] (three of a kind, Deuces)",
  "美遊: shows [Ah Jd] (a full house)",
  "美遊 collected 1700 from pot",
  "*** SUMMARY ***",
  "Total pot 1700",
  "Board [Kc 2s Js 2c 2h]",
  "Seat 1: 美遊 (button) showed [Ah Jd] and won (1700) with a full house",
  "Seat 2: 凛 (small blind) folded before Flop",
  "Seat 3: クロエ (big blind) folded before Flop",
  "Seat 4: イリヤスフィール showed [As 5h] and lost with three of a kind, Deuces",
  // hand 3
  "Poker Game #384370223: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level II (100/200) - 2025-07-13 17:22:35",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (6900 in chips)",
  "Seat 2: 凛 (6100 in chips)",
  "Seat 3: クロエ (5700 in chips)",
  "Seat 4: イリヤスフィール (5300 in chips)",
  "美遊: posts the ante 50",
  "凛: posts the ante 50",
  "クロエ: posts the ante 50",
  "イリヤスフィール: posts the ante 50",
  "クロエ: posts small blind 100",
  "イリヤスフィール: posts big blind 200",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [Ts 2s]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "美遊: folds",
  "凛: folds",
  "クロエ: raises 500 to 700",
  "イリヤスフィール: calls 700",
  "*** FLOP *** [6s 8d 3c]",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "*** TURN *** [6s 8d 3c] [2d]",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "*** RIVER *** [6s 8d 3c 2d] [Ac]",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "*** SHOW DOWN ***",
  "イリヤスフィール: shows [Kc 3s] (a pair of Threes)",
  "クロエ: shows [7d 9s] (high card)",
  "イリヤスフィール collected 1600 from pot",
  "*** SUMMARY ***",
  "Total pot 1600",
  "Board [6s 8d 3c 2d Ac]",
  "Seat 1: 美遊 folded before Flop (didn't bet)",
  "Seat 2: 凛 (button) folded before Flop (didn't bet)",
  "Seat 3: クロエ (small blind) showed [7d 9s] and lost with high card",
  "Seat 4: イリヤスフィール (big blind) showed [Kc 3s] and won (1600) with a pair of Threes",
  // hand 4
  "Poker Game #384370351: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level II (100/200) - 2025-07-13 17:23:08",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #3 is the button",
  "Seat 1: 美遊 (6850 in chips)",
  "Seat 2: 凛 (6050 in chips)",
  "Seat 3: クロエ (4950 in chips)",
  "Seat 4: イリヤスフィール (6150 in chips)",
  "美遊: posts the ante 50",
  "凛: posts the ante 50",
  "クロエ: posts the ante 50",
  "イリヤスフィール: posts the ante 50",
  "イリヤスフィール: posts small blind 100",
  "美遊: posts big blind 200",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [4h Kc]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "凛: folds",
  "クロエ: raises 400 to 600",
  "イリヤスフィール: calls 600",
  "美遊: folds",
  "*** FLOP *** [2c Js Jd]",
  "イリヤスフィール: checks",
  "クロエ: bets 533",
  "イリヤスフィール: folds",
  "Uncalled bet (533) returned to クロエ",
  "クロエ collected 1600 from pot",
  "クロエ: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 1600",
  "Board [2c Js Jd]",
  "Seat 1: 美遊 (big blind) folded before Flop",
  "Seat 2: 凛 folded before Flop (didn't bet)",
  "Seat 3: クロエ (button) collected (1600)",
  "Seat 4: イリヤスフィール (small blind) folded",
  // hand 5
  "Poker Game #384370450: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level II (100/200) - 2025-07-13 17:23:26",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #4 is the button",
  "Seat 1: 美遊 (6600 in chips)",
  "Seat 2: 凛 (6000 in chips)",
  "Seat 3: クロエ (5900 in chips)",
  "Seat 4: イリヤスフィール (5500 in chips)",
  "美遊: posts the ante 50",
  "凛: posts the ante 50",
  "クロエ: posts the ante 50",
  "イリヤスフィール: posts the ante 50",
  "美遊: posts small blind 100",
  "凛: posts big blind 200",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [4d 3c]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "クロエ: folds",
  "イリヤスフィール: folds",
  "美遊: folds",
  "Uncalled bet (100) returned to 凛",
  "凛 collected 400 from pot",
  "凛: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 400",
  "Seat 1: 美遊 (small blind) folded before Flop",
  "Seat 2: 凛 (big blind) collected (400)",
  "Seat 3: クロエ folded before Flop (didn't bet)",
  "Seat 4: イリヤスフィール (button) folded before Flop (didn't bet)",
  // hand 6
  "Poker Game #384370483: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level II (100/200) - 2025-07-13 17:23:35",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (6450 in chips)",
  "Seat 2: 凛 (6250 in chips)",
  "Seat 3: クロエ (5850 in chips)",
  "Seat 4: イリヤスフィール (5450 in chips)",
  "美遊: posts the ante 50",
  "凛: posts the ante 50",
  "クロエ: posts the ante 50",
  "イリヤスフィール: posts the ante 50",
  "凛: posts small blind 100",
  "クロエ: posts big blind 200",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [7c Th]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "イリヤスフィール: raises 400 to 600",
  "美遊: calls 600",
  "凛: folds",
  "クロエ: folds",
  "*** FLOP *** [3d 4h 7d]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** TURN *** [3d 4h 7d] [Kh]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** RIVER *** [3d 4h 7d Kh] [As]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** SHOW DOWN ***",
  "イリヤスフィール: shows [Ad 5s] (a pair of Aces)",
  "美遊: shows [4c 3c] (two pair, Fours and Threes)",
  "美遊 collected 1700 from pot",
  "*** SUMMARY ***",
  "Total pot 1700",
  "Board [3d 4h 7d Kh As]",
  "Seat 1: 美遊 (button) showed [4c 3c] and won (1700) with two pair, Fours and Threes",
  "Seat 2: 凛 (small blind) folded before Flop",
  "Seat 3: クロエ (big blind) folded before Flop",
  "Seat 4: イリヤスフィール showed [Ad 5s] and lost with a pair of Aces",
  // hand 7
  "Poker Game #384370589: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level III (140/280) - 2025-07-13 17:24:15",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (7500 in chips)",
  "Seat 2: 凛 (6100 in chips)",
  "Seat 3: クロエ (5600 in chips)",
  "Seat 4: イリヤスフィール (4800 in chips)",
  "美遊: posts the ante 70",
  "凛: posts the ante 70",
  "クロエ: posts the ante 70",
  "イリヤスフィール: posts the ante 70",
  "クロエ: posts small blind 140",
  "イリヤスフィール: posts big blind 280",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [2h Ad]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "美遊: folds",
  "凛: raises 280 to 560",
  "クロエ: calls 560",
  "イリヤスフィール: calls 560",
  "*** FLOP *** [6c 5c Qc]",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "凛: checks",
  "*** TURN *** [6c 5c Qc] [2d]",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "凛: checks",
  "*** RIVER *** [6c 5c Qc 2d] [As]",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "凛: checks",
  "*** SHOW DOWN ***",
  "イリヤスフィール: shows [3h Ac] (a pair of Aces)",
  "凛: shows [2h Ad] (two pair, Aces and Deuces)",
  "クロエ: shows [8h Jc] (high card)",
  "凛 collected 1960 from pot",
  "*** SUMMARY ***",
  "Total pot 1960",
  "Board [6c 5c Qc 2d As]",
  "Seat 1: 美遊 folded before Flop (didn't bet)",
  "Seat 2: 凛 (button) showed [2h Ad] and won (1960) with two pair, Aces and Deuces",
  "Seat 3: クロエ (small blind) showed [8h Jc] and lost with high card",
  "Seat 4: イリヤスフィール (big blind) showed [3h Ac] and lost with a pair of Aces",
  // hand 8
  "Poker Game #384370731: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level III (140/280) - 2025-07-13 17:24:52",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #3 is the button",
  "Seat 1: 美遊 (7430 in chips)",
  "Seat 2: 凛 (7430 in chips)",
  "Seat 3: クロエ (4970 in chips)",
  "Seat 4: イリヤスフィール (4170 in chips)",
  "美遊: posts the ante 70",
  "凛: posts the ante 70",
  "クロエ: posts the ante 70",
  "イリヤスフィール: posts the ante 70",
  "イリヤスフィール: posts small blind 140",
  "美遊: posts big blind 280",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [Td Qs]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "凛: raises 280 to 560",
  "クロエ: calls 560",
  "イリヤスフィール: calls 560",
  "美遊: calls 560",
  "*** FLOP *** [3h 6h Ac]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "凛: bets 280",
  "クロエ: calls 280",
  "イリヤスフィール: calls 280",
  "美遊: calls 280",
  "*** TURN *** [3h 6h Ac] [Qd]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "凛: checks",
  "クロエ: checks",
  "*** RIVER *** [3h 6h Ac Qd] [4d]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "凛: bets 280",
  "クロエ: folds",
  "イリヤスフィール: calls 280",
  "美遊: calls 280",
  "*** SHOW DOWN ***",
  "凛: shows [Td Qs] (a pair of Queens)",
  "イリヤスフィール: shows [Qh As] (two pair, Aces and Queens)",
  "美遊: shows [3s Kc] (a pair of Threes)",
  "イリヤスフィール collected 4480 from pot",
  "*** SUMMARY ***",
  "Total pot 4480",
  "Board [3h 6h Ac Qd 4d]",
  "Seat 1: 美遊 (big blind) showed [3s Kc] and lost with a pair of Threes",
  "Seat 2: 凛 showed [Td Qs] and lost with a pair of Queens",
  "Seat 3: クロエ (button) folded",
  "Seat 4: イリヤスフィール (small blind) showed [Qh As] and won (4480) with two pair, Aces and Queens",
  // hand 9
  "Poker Game #384370919: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level III (140/280) - 2025-07-13 17:25:40",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #4 is the button",
  "Seat 1: 美遊 (6240 in chips)",
  "Seat 2: 凛 (6240 in chips)",
  "Seat 3: クロエ (4060 in chips)",
  "Seat 4: イリヤスフィール (7460 in chips)",
  "美遊: posts the ante 70",
  "凛: posts the ante 70",
  "クロエ: posts the ante 70",
  "イリヤスフィール: posts the ante 70",
  "美遊: posts small blind 140",
  "凛: posts big blind 280",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [Jc 8d]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "クロエ: raises 560 to 840",
  "イリヤスフィール: calls 840",
  "美遊: calls 840",
  "凛: folds",
  "*** FLOP *** [Qd Ac Ad]",
  "美遊: checks",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "*** TURN *** [Qd Ac Ad] [7c]",
  "美遊: checks",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "*** RIVER *** [Qd Ac Ad 7c] [4s]",
  "美遊: checks",
  "クロエ: checks",
  "イリヤスフィール: checks",
  "*** SHOW DOWN ***",
  "クロエ: shows [7h 4h] (two pair, Aces and Sevens)",
  "イリヤスフィール: shows [Qs Js] (two pair, Aces and Queens)",
  "美遊: shows [4c 3h] (two pair, Aces and Fours)",
  "イリヤスフィール collected 3080 from pot",
  "*** SUMMARY ***",
  "Total pot 3080",
  "Board [Qd Ac Ad 7c 4s]",
  "Seat 1: 美遊 (small blind) showed [4c 3h] and lost with two pair, Aces and Fours",
  "Seat 2: 凛 (big blind) folded before Flop",
  "Seat 3: クロエ showed [7h 4h] and lost with two pair, Aces and Sevens",
  "Seat 4: イリヤスフィール (button) showed [Qs Js] and won (3080) with two pair, Aces and Queens",
  // hand 10
  "Poker Game #384371065: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level IV (200/400) - 2025-07-13 17:26:19",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (5330 in chips)",
  "Seat 2: 凛 (5890 in chips)",
  "Seat 3: クロエ (3150 in chips)",
  "Seat 4: イリヤスフィール (9630 in chips)",
  "美遊: posts the ante 100",
  "凛: posts the ante 100",
  "クロエ: posts the ante 100",
  "イリヤスフィール: posts the ante 100",
  "凛: posts small blind 200",
  "クロエ: posts big blind 400",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [4s 8s]",
  "Dealt to クロエ",
  "Dealt to イリヤスフィール",
  "イリヤスフィール: raises 800 to 1200",
  "美遊: calls 1200",
  "凛: folds",
  "クロエ: raises 1850 to 3050 and is all-in",
  "イリヤスフィール: calls 3050",
  "美遊: raises 2180 to 5230 and is all-in",
  "イリヤスフィール: calls 5230",
  "*** FLOP *** [9s 5s 5d]",
  "*** TURN *** [9s 5s 5d] [Tc]",
  "*** RIVER *** [9s 5s 5d Tc] [Qh]",
  "*** SHOW DOWN ***",
  "美遊: shows [Jh 8c] (a straight)",
  "クロエ: shows [Qd 2c] (two pair, Queens and Fives)",
  "イリヤスフィール: shows [5c Ad] (three of a kind, Fives)",
  "美遊 collected 14110 from pot",
  "クロエ finished the tournament in 4th place",
  "*** SUMMARY ***",
  "Total pot 14110",
  "Board [9s 5s 5d Tc Qh]",
  "Seat 1: 美遊 (button) showed [Jh 8c] and won (14110) with a straight",
  "Seat 2: 凛 (small blind) folded before Flop",
  "Seat 3: クロエ (big blind) showed [Qd 2c] and lost with two pair, Queens and Fives",
  "Seat 4: イリヤスフィール showed [5c Ad] and lost with three of a kind, Fives",
  // hand 11
  "Poker Game #384371168: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level IV (200/400) - 2025-07-13 17:26:49",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (14110 in chips)",
  "Seat 2: 凛 (5590 in chips)",
  "Seat 4: イリヤスフィール (4300 in chips)",
  "美遊: posts the ante 100",
  "凛: posts the ante 100",
  "イリヤスフィール: posts the ante 100",
  "イリヤスフィール: posts small blind 200",
  "美遊: posts big blind 400",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [4s Jc]",
  "Dealt to イリヤスフィール",
  "凛: folds",
  "イリヤスフィール: raises 1000 to 1400",
  "美遊: calls 1400",
  "*** FLOP *** [6c 5s 9h]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** TURN *** [6c 5s 9h] [8d]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** RIVER *** [6c 5s 9h 8d] [7s]",
  "イリヤスフィール: checks",
  "美遊: checks",
  "*** SHOW DOWN ***",
  "美遊: shows [6d 5c] (a straight)",
  "イリヤスフィール: shows [8h Kh] (a straight)",
  "イリヤスフィール collected 1550 from pot",
  "美遊 collected 1550 from pot",
  "*** SUMMARY ***",
  "Total pot 3100",
  "Board [6c 5s 9h 8d 7s]",
  "Seat 1: 美遊 (big blind) showed [6d 5c] and won (1550) with a straight",
  "Seat 2: 凛 (button) folded before Flop (didn't bet)",
  "Seat 4: イリヤスフィール (small blind) showed [8h Kh] and won (1550) with a straight",
  // hand 12
  "Poker Game #384371305: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level IV (200/400) - 2025-07-13 17:27:13",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #4 is the button",
  "Seat 1: 美遊 (14160 in chips)",
  "Seat 2: 凛 (5490 in chips)",
  "Seat 4: イリヤスフィール (4350 in chips)",
  "美遊: posts the ante 100",
  "凛: posts the ante 100",
  "イリヤスフィール: posts the ante 100",
  "美遊: posts small blind 200",
  "凛: posts big blind 400",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [Kh Td]",
  "Dealt to イリヤスフィール",
  "イリヤスフィール: raises 800 to 1200",
  "美遊: calls 1200",
  "凛: calls 1200",
  "*** FLOP *** [Jd 7c 9s]",
  "美遊: checks",
  "凛: checks",
  "イリヤスフィール: checks",
  "*** TURN *** [Jd 7c 9s] [2s]",
  "美遊: checks",
  "凛: checks",
  "イリヤスフィール: checks",
  "*** RIVER *** [Jd 7c 9s 2s] [Qc]",
  "美遊: checks",
  "凛: raises 3790 to 4190 and is all-in",
  "イリヤスフィール: folds",
  "美遊: folds",
  "Uncalled bet (4190) returned to 凛",
  "凛 collected 3900 from pot",
  "凛: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 3900",
  "Board [Jd 7c 9s 2s Qc]",
  "Seat 1: 美遊 (small blind) folded",
  "Seat 2: 凛 (big blind) collected (3900)",
  "Seat 4: イリヤスフィール (button) folded",
  // hand 13
  "Poker Game #384371459: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:27:56",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (12860 in chips)",
  "Seat 2: 凛 (8090 in chips)",
  "Seat 4: イリヤスフィール (3050 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "イリヤスフィール: posts the ante 140",
  "凛: posts small blind 280",
  "イリヤスフィール: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [8s 5c]",
  "Dealt to イリヤスフィール",
  "美遊: raises 1120 to 1680",
  "凛: folds",
  "イリヤスフィール: raises 1230 to 2910 and is all-in",
  "美遊: calls 2910",
  "*** FLOP *** [9h 6d 7h]",
  "*** TURN *** [9h 6d 7h] [7d]",
  "*** RIVER *** [9h 6d 7h 7d] [5d]",
  "*** SHOW DOWN ***",
  "イリヤスフィール: shows [Qc Jd] (a pair of Sevens)",
  "美遊: shows [Th Tc] (two pair, Tens and Sevens)",
  "美遊 collected 6520 from pot",
  "イリヤスフィール finished the tournament in 3rd place",
  "*** SUMMARY ***",
  "Total pot 6520",
  "Board [9h 6d 7h 7d 5d]",
  "Seat 1: 美遊 (button) showed [Th Tc] and won (6520) with two pair, Tens and Sevens",
  "Seat 2: 凛 (small blind) folded before Flop",
  "Seat 4: イリヤスフィール (big blind) showed [Qc Jd] and lost with a pair of Sevens",
  // hand 14
  "Poker Game #384371520: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:28:20",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (16330 in chips)",
  "Seat 2: 凛 (7670 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "凛: posts small blind 280",
  "美遊: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [As 5d]",
  "凛: raises 560 to 1120",
  "美遊: folds",
  "Uncalled bet (1120) returned to 凛",
  "凛 collected 840 from pot",
  "凛: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 840",
  "Seat 1: 美遊 (big blind) folded before Flop",
  "Seat 2: 凛 (button) collected (840)",
  // hand 15
  "Poker Game #384371599: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:28:28",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (15630 in chips)",
  "Seat 2: 凛 (8370 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "美遊: posts small blind 280",
  "凛: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [3c 6d]",
  "美遊: folds",
  "Uncalled bet (280) returned to 凛",
  "凛 collected 840 from pot",
  "凛: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 840",
  "Seat 1: 美遊 (button) folded before Flop",
  "Seat 2: 凛 (big blind) collected (840)",
  // hand 16
  "Poker Game #384371620: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:28:34",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (15210 in chips)",
  "Seat 2: 凛 (8790 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "凛: posts small blind 280",
  "美遊: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [8d 2h]",
  "凛: folds",
  "Uncalled bet (280) returned to 美遊",
  "美遊 collected 840 from pot",
  "美遊: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 840",
  "Seat 1: 美遊 (big blind) collected (840)",
  "Seat 2: 凛 (button) folded before Flop",
  // hand 17
  "Poker Game #384371640: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:28:41",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (15630 in chips)",
  "Seat 2: 凛 (8370 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "美遊: posts small blind 280",
  "凛: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [2c Qd]",
  "美遊: raises 1400 to 1960",
  "凛: folds",
  "Uncalled bet (1960) returned to 美遊",
  "美遊 collected 840 from pot",
  "美遊: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 840",
  "Seat 1: 美遊 (button) collected (840)",
  "Seat 2: 凛 (big blind) folded before Flop",
  // hand 18
  "Poker Game #384371675: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:28:48",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (16330 in chips)",
  "Seat 2: 凛 (7670 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "凛: posts small blind 280",
  "美遊: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [7h 6h]",
  "凛: raises 560 to 1120",
  "美遊: calls 1120",
  "*** FLOP *** [Jc Qd Ac]",
  "美遊: checks",
  "凛: bets 831",
  "美遊: calls 831",
  "*** TURN *** [Jc Qd Ac] [9s]",
  "美遊: checks",
  "凛: checks",
  "*** RIVER *** [Jc Qd Ac 9s] [9c]",
  "美遊: checks",
  "凛: checks",
  "*** SHOW DOWN ***",
  "美遊: shows [Qc 7s] (two pair, Queens and Nines)",
  "凛: mucks hand",
  "美遊 collected 4182 from pot",
  "*** SUMMARY ***",
  "Total pot 4182",
  "Board [Jc Qd Ac 9s 9c]",
  "Seat 1: 美遊 (big blind) showed [Qc 7s] and won (4182) with two pair, Queens and Nines",
  "Seat 2: 凛 (button) mucked",
  // hand 19
  "Poker Game #384371773: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:29:21",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (18421 in chips)",
  "Seat 2: 凛 (5579 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "美遊: posts small blind 280",
  "凛: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [9c Ks]",
  "美遊: raises 1400 to 1960",
  "凛: folds",
  "Uncalled bet (1960) returned to 美遊",
  "美遊 collected 840 from pot",
  "美遊: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 840",
  "Seat 1: 美遊 (button) collected (840)",
  "Seat 2: 凛 (big blind) folded before Flop",
  // hand 20
  "Poker Game #384371859: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:29:31",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (19121 in chips)",
  "Seat 2: 凛 (4879 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "凛: posts small blind 280",
  "美遊: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [7s 5d]",
  "凛: folds",
  "Uncalled bet (280) returned to 美遊",
  "美遊 collected 840 from pot",
  "美遊: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 840",
  "Seat 1: 美遊 (big blind) collected (840)",
  "Seat 2: 凛 (button) folded before Flop",
  // hand 21
  "Poker Game #384371882: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:29:38",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #1 is the button",
  "Seat 1: 美遊 (19541 in chips)",
  "Seat 2: 凛 (4459 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "美遊: posts small blind 280",
  "凛: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [5c 8d]",
  "美遊: raises 1400 to 1960",
  "凛: folds",
  "Uncalled bet (1960) returned to 美遊",
  "美遊 collected 840 from pot",
  "美遊: doesn't show hand ",
  "*** SUMMARY ***",
  "Total pot 840",
  "Seat 1: 美遊 (button) collected (840)",
  "Seat 2: 凛 (big blind) folded before Flop",
  // hand 22
  "Poker Game #384371912: Tournament #384370064, text_rank_stage_name_stage000 Hold'em No Limit - Level V (280/560) - 2025-07-13 17:29:46",
  "Table 'text_rank_stage_name_stage000' 6-max Seat #2 is the button",
  "Seat 1: 美遊 (20241 in chips)",
  "Seat 2: 凛 (3759 in chips)",
  "美遊: posts the ante 140",
  "凛: posts the ante 140",
  "凛: posts small blind 280",
  "美遊: posts big blind 560",
  "*** HOLE CARDS ***",
  "Dealt to 美遊",
  "Dealt to 凛 [4s 3s]",
  "凛: raises 3059 to 3619 and is all-in",
  "美遊: calls 3619",
  "*** FLOP *** [2d 9h 8d]",
  "*** TURN *** [2d 9h 8d] [Th]",
  "*** RIVER *** [2d 9h 8d Th] [2s]",
  "*** SHOW DOWN ***",
  "凛: shows [4s 3s] (a pair of Deuces)",
  "美遊: shows [As Kd] (a pair of Deuces)",
  "美遊 collected 7518 from pot",
  "凛 finished the tournament in 2nd place",
  "*** SUMMARY ***",
  "Total pot 7518",
  "Board [2d 9h 8d Th 2s]",
  "Seat 1: 美遊 (big blind) showed [As Kd] and won (7518) with a pair of Deuces",
  "Seat 2: 凛 (button) showed [4s 3s] and lost with a pair of Deuces",
].join('\n')

test('ApiEventsからPokerStars形式のログを生成できる', async () => {
  const dbMock = new PokerChaseDB(indexedDB, IDBKeyRange)
  const service = new PokerChaseService({ db: dbMock })

  const sessionEvent = event_timeline.find(e => e.ApiTypeId === ApiType.EVT_SESSION_DETAILS)!
  service.session.name = sessionEvent.Name
  service.session.battleType = BattleType.SIT_AND_GO

  const seatEvent = event_timeline.find(e => e.ApiTypeId === ApiType.EVT_PLAYER_SEAT_ASSIGNED)!
  seatEvent.TableUsers?.forEach(user => {
    service.session.players.set(user.UserId, {
      name: user.UserName,
      rank: user.Rank.RankName
    })
  })

  const actual = await new Promise<string[]>((resolve, reject) => {
    const actualHandLogs: string[] = []
    service.handLogStream.on('data', (event: HandLogEvent) => {
      if (event.type === 'update' && event.entries)
        actualHandLogs.push(event.entries.map(({ text }) => text).join('\n'))
    })
      .on('end', () => resolve(actualHandLogs))
      .on('error', (error: Error) => reject(error))
    Readable.from(event_timeline).pipe(service.handLogStream)
  })
  expect(actual.join('\n')).toEqual(expected)
})
